### ISSUE TITLE
Token Exposure

### ISSUE THREAD

**Issue by kylekarpack** [fredcorr/portfolio#7]
Hi, I was doing a quick security review for the [Sanity Vercel Dashboard](https://github.com/robinpyon/sanity-plugin-dashboard-widget-vercel) plugin and I found a publicly available secret for your Vercel account here: https://github.com/fredcorr/portfolio/blob/bfcff1a5dd557bdbc71ba444c8c66be4e31c9b7c/build/studio/dashboardConfig.js#L28

It appears that secret is currently valid and allows full control of your Vercel account. You'll want to make sure to cycle that secret since it's been compromised. Cheers,

Kyle

**Comment by fredcorr** [comment]
Thanks a lot for this Kyle. Completely forgot this repo is public and such file is accessible from everyone.

Thanks.
Agains
